### ISSUE TITLE
Issue with 2.1.1 spring-cloud-function-dependencies

### ISSUE THREAD

**Issue by kubarzeplinski** [Azure-Samples/hello-spring-function-azure#1]
Hi,
do you plan to upgrade spring-cloud-function-dependencies version in this sample project? I got _Failed to locate main class exception_ for 2.1.1 spring-cloud-function-dependencies.

Stack: java.lang.IllegalStateException: Failed to discover main class. An attempt was made to discover main class as 'MAIN_CLASS' environment variable, system property as well as entry in META-INF/MANIFEST.MF (in that order).
[26.11.2019 15:35:50] 	at org.springframework.cloud.function.context.AbstractSpringFunctionAdapterInitializer.getStartClass(AbstractSpringFunctionAdapterInitializer.java:283)
[26.11.2019 15:35:50] 	at org.springframework.cloud.function.context.AbstractSpringFunctionAdapterInitializer.<init>(AbstractSpringFunctionAdapterInitializer.java:99)
[26.11.2019 15:35:50] 	at org.springframework.cloud.function.adapter.azure.AzureSpringBootRequestHandler.<init>(AzureSpringBootRequestHandler.java:44)

**Comment by jdubois** [comment]
Thanks a lot @kubarzeplinski !!!
In fact I corrected it on my own project at https://github.com/jdubois/hello-spring-function-azure and didn't make the change here.

Let me correct that:

- I'm going to copy my changes to this repo
- I will then archive my own repo, so I don't do this again

I'll keep you updated on this ticket, but meanwhile you can use my https://github.com/jdubois/hello-spring-function-azure project, which is already good.

**Comment by jdubois** [comment]
@kubarzeplinski  everything is done, the "main class" issue should be solved with https://github.com/Azure-Samples/hello-spring-function-azure/commit/f0c94173a72b16d2581950aa9568821d9cde7ed8

I notice that you are using an even newer Spring Boot version (I'm on 2.2.0, you are on 2.2.1), can you check if everything is fine on your side? Then we can close the ticket.

**Comment by kubarzeplinski** [comment]
Hi @jdubois,
i fetched your change. I think that you should upgrade spring-cloud-function-dependencies in pom.xml also. This sample project still doesn't work for me with 2.1.1.RELEASE and the latest 3.0.0.RELEASE version. It will be good to use 3.0.0.RELEASE. It is available in Maven repository since yesterday.

**Comment by jdubois** [comment]
Thanks @kubarzeplinski - I tested again with Spring Boot 2.2.0 and it was working, but you are correct, so I have upgraded:

- Upgrade to the latest Spring Boot 2.2.1 release in https://github.com/Azure-Samples/hello-spring-function-azure/commit/f06a39819847d0ee3408f65ff93a44bc286e6b66
- Upgrade to the latest Spring Cloud Function 3.0.0 release in https://github.com/Azure-Samples/hello-spring-function-azure/commit/35d01ce2bed3b04d612ff56556f8298300905e90

I have tested again and everything works fine.

Your issue is different, this is because the main class could not be found, so I guess you didn't see the trick here: https://github.com/Azure-Samples/hello-spring-function-azure/blob/35d01ce2bed3b04d612ff56556f8298300905e90/pom.xml#L114

Indeed, that trick isn't very developer-friendly, and this should be automated (I'm guessing by the Spring Cloud team).

**Comment by kubarzeplinski** [comment]
Thank you @jdubois. I don't know why, but i still have this issue with main class. I added new system variable with key MAIN_CLASS and it works, but i think that it is not recommended. Which mvn command do you use to package and run this project? I use `mvn clean package azure-functions:run`.

**Comment by jdubois** [comment]
@kubarzeplinski I'm doing `mvn clean package azure-functions:deploy` but I don't understand why there would be a difference, it's hard-coded in the configuration. Did you check you have the correct package+name for your class?

**Comment by kubarzeplinski** [comment]
Hi @jdubois, i confirm that this sample project with all you your changes works on Azure (i use the same command as you). I would like to test this app locally before deploying this. That is why i use `azure-functions:run` instead of `azure-functions:deploy`. This is recommended way for business applications. :)). I have this issue with main class when i run this app locally in my IDE.

**Comment by jdubois** [comment]
Oh thanks for the explanation @kubarzeplinski ! Indeed, I didn't test locally, but I wasn't expecting there would be a difference, it's supposed to be the same environment! Maybe there's a version mismatch between your local environment and the one on Azure? This would be a case for support, as I don't think this should happen at all.

**Comment by kubarzeplinski** [comment]
@jdubois, i see MAIN_CLASS property in application settings tab in my App Service. I think that this was added automatically during deployment of this app. It does't work without this setting.
![image](https://user-images.githubusercontent.com/27897193/69793416-a8b83f80-11c8-11ea-94ec-12b5704f5849.png)

**Comment by jdubois** [comment]
Indeed @kubarzeplinski this setting is mandatory.

- I would love to get rid of this configuration, and I guess there is some way to automate this inside the plugin.
- Then I force this setting in the plugin, so it should both work for "deploy" and "run". So for me this is a bug in the plugin.

I'm going to fill a ticket for this on the plugin repository, and I will link it here for follow up.

As this issue is with a specific Maven goal, I'll then close this ticket.
